    <option value="Abangares">Abangares</option>
    <option value="Acosta">Acosta</option>
    <option value="Aguirre">Aguirre</option>
    <option value="Alajuela">Alajuela</option>
    <option value="Alajuelita">Alajuelita</option>
    <option value="Alfaro Ruíz">Alfaro Ruíz</option>
    <option value="Alvarado">Alvarado</option>
    <option value="Aserrí">Aserrí</option>
    <option value="Atenas">Atenas</option>
    <option value="Bagaces">Bagaces</option>
    <option value="Barva">Barva</option>
    <option value="Belén">Belén</option>
    <option value="Buenos Aires">Buenos Aires</option>
    <option value="Cañas">Cañas</option>
    <option value="Carrillo">Carrillo</option>
    <option value="Cartago">Cartago</option>
    <option value="Corredores">Corredores</option>
    <option value="Coto Brus">Coto Brus</option>
    <option value="Currridabat">Currridabat</option>
    <option value="Desamparados">Desamparados</option>
    <option value="Dota">Dota</option>
    <option value="El Guarco">El Guarco</option>
    <option value="Escazú">Escazú</option>
    <option value="Esparza">Esparza</option>
    <option value="Flores">Flores</option>
    <option value="Garabito">Garabito</option>
    <option value="Goicoechea">Goicoechea</option>
    <option value="Golfito">Golfito</option>
    <option value="Grecia">Grecia</option>
    <option value="Guácimo">Guácimo</option>
    <option value="Guatuso">Guatuso</option>
    <option value="Heredia">Heredia</option>
    <option value="Hojancha">Hojancha</option>
    <option value="Jiménez">Jiménez</option>
    <option value="La Cruz">La Cruz</option>
    <option value="La Unión">La Unión</option>
    <option value="León Cortés">León Cortés</option>
    <option value="Liberia">Liberia</option>
    <option value="Limón">Limón</option>
    <option value="Los Chiles">Los Chiles</option>
    <option value="Matina">Matina</option>
    <option value="Montes de Oca">Montes de Oca</option>
    <option value="Montes de Oro">Montes de Oro</option>
    <option value="Mora">Mora</option>
    <option value="Moravia">Moravia</option>
    <option value="Nandayure">Nandayure</option>
    <option value="Naranjo">Naranjo</option>
    <option value="Nicoya">Nicoya</option>
    <option value="Oreamuno">Oreamuno</option>
    <option value="Orotina">Orotina</option>
    <option value="Osa">Osa</option>
    <option value="Palmares">Palmares</option>
    <option value="Paraíso">Paraíso</option>
    <option value="Parrita">Parrita</option>
    <option value="Pérez Zeledón">Pérez Zeledón</option>
    <option value="Poás">Poás</option>
    <option value="Pococí">Pococí</option>
    <option value="Puntarenas">Puntarenas</option>
    <option value="Puriscal">Puriscal</option>
    <option value="San Carlos">San Carlos</option>
    <option value="San Isidro">San Isidro</option>
    <option value="San José">San José</option>
    <option value="San Mateo">San Mateo</option>
    <option value="San Pablo">San Pablo</option>
    <option value="San Rafael">San Rafael</option>
    <option value="San Ramón">San Ramón</option>
    <option value="Santa Ana">Santa Ana</option>
    <option value="Santa Bárbara">Santa Bárbara</option>
    <option value="Santa Cruz">Santa Cruz</option>
    <option value="Santo Domingo">Santo Domingo</option>
    <option value="Sarapiquí">Sarapiquí</option>
    <option value="Siquirres">Siquirres</option>
    <option value="Talamanca">Talamanca</option>
    <option value="Tarrazú">Tarrazú</option>
    <option value="Tibás">Tibás</option>
    <option value="Tilarán">Tilarán</option>
    <option value="Turrialba">Turrialba</option>
    <option value="Turrubares">Turrubares</option>
    <option value="Upala">Upala</option>
    <option value="Valverde Vega">Valverde Vega</option>
    <option value="Vásquez de Coronado">Vásquez de Coronado</option>